name: pointycastle
version: 3.0.1
description: A Dart library implementing cryptographic algorithms and primitives, modeled on the BouncyCastle library.
homepage: https://github.com/bcgit/pc-dart
environment:
  sdk: '>=2.12.0-0 <3.0.0'


dev_dependencies:
  benchmark_harness:  ^2.0.0
  matcher: ^0.12.10
  test: ^1.17.2
  pedantic: ^1.11.0
